# Generated by Django 4.2 on 2025-11-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='servicios.servicio')),
            ],
        ),
    ]
