# Generated by Django 4.2 on 2025-11-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='nombre',
            new_name='nombre_sede',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='servicio',
        ),
    ]
