# Generated by Django 4.2 on 2025-11-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_rename_nombre_sede_nombre_sede_remove_sede_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='direccion',
        ),
    ]
