# Generated by Django 4.2 on 2025-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0003_remove_sede_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
