# Generated by Django 4.2 on 2025-11-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0004_sede_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='direccion',
        ),
    ]
