# Generated by Django 4.2 on 2025-11-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('responsables', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_udea', models.CharField(max_length=50, unique=True)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('codigo_ips', models.CharField(max_length=50, unique=True)),
                ('codigo_ecri', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('clasificacion_misional', models.CharField(max_length=100)),
                ('clasificacion_ips', models.CharField(max_length=100)),
                ('clasificacion_riesgo', models.CharField(max_length=100)),
                ('registro_invima', models.CharField(max_length=100)),
                ('vida_util', models.IntegerField()),
                ('fecha_adquisicion', models.DateField()),
                ('propietario', models.CharField(max_length=100)),
                ('fecha_fabricacion', models.DateField()),
                ('nit', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=100)),
                ('garantia', models.BooleanField()),
                ('finalizacion_garantia', models.DateField()),
                ('forma_adquisicion', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('valor_compra', models.CharField(max_length=50)),
                ('hoja_de_vida', models.BooleanField()),
                ('registro_importacion', models.BooleanField()),
                ('manual_operacion', models.BooleanField()),
                ('manual_mantenimiento', models.BooleanField()),
                ('guia_rapida', models.BooleanField()),
                ('instructivo_de_manejo', models.BooleanField()),
                ('protocolo_mantenimiento', models.BooleanField()),
                ('frecuencia_metrologia', models.CharField(max_length=100)),
                ('mantenimiento', models.BooleanField()),
                ('frecuencia_mantenimiento', models.IntegerField(max_length=100)),
                ('calibracion', models.BooleanField()),
                ('frecuencia_calibracion', models.IntegerField(max_length=100)),
                ('magnitud', models.CharField(max_length=100)),
                ('rango_medicion', models.CharField(max_length=100)),
                ('resolucion', models.CharField(max_length=100)),
                ('rango_trabajo', models.CharField(max_length=100)),
                ('error_maximo_permitido', models.CharField(max_length=100)),
                ('voltaje', models.CharField(max_length=50)),
                ('corriente', models.CharField(max_length=50)),
                ('humedad_relativa', models.CharField(max_length=50)),
                ('temperatura_operacion', models.CharField(max_length=50)),
                ('dimensiones', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=50)),
                ('otros', models.TextField()),
                ('responsable_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='responsables.responsable')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='sedes.sede')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='servicios.servicio')),
            ],
        ),
    ]
