# Generated by Django 4.2 on 2025-11-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipos',
            name='frecuencia_calibracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='frecuencia_mantenimiento',
            field=models.IntegerField(),
        ),
    ]
