# Generated by Django 4.2 on 2025-12-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_sede'),
        ('sedes', '0005_remove_sede_direccion'),
        ('equipos', '0004_add_maintenance_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='acquisition_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='calibration_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='calibration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='current',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fabrication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_import_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_instruction_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_life_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_maintenance_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_maintenance_protocol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_operation_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='has_quick_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='in_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='invima_record',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='ips_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='ips_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='magnitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='maintenance_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='maintenance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='max_permitted_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='metrology_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='misional_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='operating_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='physical_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='purchase_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='relative_humidity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='risk_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='sedes.sede'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='useful_life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='voltage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='work_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
