# Generated by Django 4.2 on 2025-11-22 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_rename_nombre_sede_nombre_sede_remove_sede_servicio'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='sede',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='sedes.sede'),
            preserve_default=False,
        ),
    ]
